import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { once } from "node:events";
import { createInspectorServer } from "../src/lib/inspector-http.js";
import { emptyLedger } from "../src/lib/ledger.js";
import { writeJsonAtomic } from "../src/lib/json.js";
import { closeProductDb, openProductDb, updateSubmission } from "../src/lib/product-db.js";

function record(id, lock, status="ACTIVE", title="Type Script Builder") { return {schema:"ckb-degree-proof-record/v1",status,payload:{schema:"ckbuilder-credential/v2",credentialId:id,credentialType:"Builder Milestone",issuer:{issuerId:`0x${"aa".repeat(32)}`,name:"CKBuilder",lockHash:`0x${"bb".repeat(32)}`},subject:{recipientLockHash:lock,identityCommitment:`0x${"cc".repeat(32)}`},award:{title,field:"CKB",classification:"Builder Milestone",issuedAt:"2026-08-08"},document:{hashAlgorithm:"sha256",hash:`0x${"dd".repeat(32)}`,fileName:"proof.json"},createdAt:"2026-08-08T00:00:00.000Z"},issuerPublicKeyPem:"public",signature:"sig"}; }
async function withApp(options,fn){const root=fs.mkdtempSync(path.join(os.tmpdir(),"ckbuilder-v4http-")),pub=path.join(root,"public"),data=path.join(root,"data");fs.mkdirSync(pub);fs.mkdirSync(data);fs.writeFileSync(path.join(pub,"index.html"),"<title>v4</title>");const ledger=emptyLedger();for(const r of options.records??[])ledger.credentials[r.payload.credentialId]=r;writeJsonAtomic(path.join(data,"ledger.json"),ledger);const db=openProductDb(path.join(data,"p.sqlite"));const config={ROOT_DIR:root,DATA_DIR:data,PRODUCT_DB_PATH:path.join(data,"p.sqlite"),APP_NETWORK:"devnet",CKB_RPC_URL:"http://127.0.0.1:9",ISSUER_LOCK_HASH:`0x${"11".repeat(32)}`,PUBLIC_BASE_URL:"http://example.test",AI_ENABLED:true,AI_DEFAULT_PROVIDER:"openai",AI_DEFAULT_MODEL:"gpt-4.1-mini",PUBLIC_DIRECTORY_ENABLED:options.directory===true};const server=createInspectorServer({config,publicDir:pub,productDb:db,learningOverview:()=>({summary:{}}),inspectCredential:async()=>({})});server.listen(0,"127.0.0.1");await once(server,"listening");try{await fn({base:`http://127.0.0.1:${server.address().port}`,db,config})}finally{await new Promise(r=>server.close(r));closeProductDb(db)}}
const submission={applicantName:"Builder",applicantEmail:"b@example.com",recipientLockHash:`0x${"22".repeat(32)}`,credentialType:"Builder Milestone",credentialTitle:"Type Script Builder",category:"CKB",evidence:["https://github.com/example/repo"]};

test("v4 readiness and public stats endpoints are operational",async()=>withApp({},async({base})=>{let r=await fetch(`${base}/api/ready`);assert.equal(r.status,200);assert.equal((await r.json()).ok,true);r=await fetch(`${base}/api/stats`);const s=await r.json();assert.equal(s.credentials,0);assert.equal(s.uniqueBuilders,0);}));

test("v4 public directory is privacy-disabled by default",async()=>withApp({},async({base})=>{const r=await fetch(`${base}/api/directory`);assert.equal(r.status,404);assert.equal((await r.json()).error,"DIRECTORY_DISABLED");}));

test("v4 enabled directory supports search filters and pagination",async()=>{const lock=`0x${"33".repeat(32)}`;await withApp({directory:true,records:[record("C-A",lock,"ACTIVE","Rust Type Script"),record("C-B",lock,"REVOKED","Fiber Builder")]},async({base})=>{let r=await fetch(`${base}/api/directory?q=Rust&status=ACTIVE`);let b=await r.json();assert.equal(b.total,1);assert.equal(b.items[0].credentialId,"C-A");r=await fetch(`${base}/api/directory?limit=1&offset=1`);b=await r.json();assert.equal(b.items.length,1);assert.equal(b.total,2);});});

test("v4 tracking response includes timeline and applicant can cancel",async()=>withApp({},async({base})=>{let r=await fetch(`${base}/api/submissions`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(submission)});const c=await r.json();r=await fetch(`${base}/api/submissions/${c.id}?token=${encodeURIComponent(c.trackingToken)}`);let item=await r.json();assert.equal(item.timeline[0].event_type,"SUBMITTED");r=await fetch(`${base}/api/submissions/${c.id}/cancel`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({trackingToken:c.trackingToken})});item=await r.json();assert.equal(item.status,"CANCELLED");}));

test("v4 resubmission endpoint requires requested-changes state",async()=>withApp({},async({base,db})=>{let r=await fetch(`${base}/api/submissions`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(submission)});const c=await r.json();r=await fetch(`${base}/api/submissions/${c.id}/resubmit`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({trackingToken:c.trackingToken,evidence:["new"]})});assert.equal(r.status,409);updateSubmission(db,c.id,{status:"CHANGES_REQUESTED",reviewerNotes:"more"},"reviewer");r=await fetch(`${base}/api/submissions/${c.id}/resubmit`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({trackingToken:c.trackingToken,evidence:["https://github.com/example/new"],notes:"updated"})});const item=await r.json();assert.equal(r.status,200);assert.equal(item.status,"SUBMITTED");}));

test("v4 config advertises directory flag and BYOK providers only",async()=>withApp({directory:true},async({base})=>{const b=await (await fetch(`${base}/api/config`)).json();assert.equal(b.publicDirectoryEnabled,true);assert.ok(b.aiProviders.some(p=>p.id==="gemini"));assert.equal(JSON.stringify(b).includes("apiKey"),false);}));
