import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { once } from "node:events";
import { initializeIssuer } from "../src/lib/credential-service.js";
import { closeProductDb, createSubmission, openProductDb } from "../src/lib/product-db.js";
import { createIssuerServer } from "../src/lib/issuer-http.js";

async function setup(){const root=fs.mkdtempSync(path.join(os.tmpdir(),"ckbuilder-v4issuer-")),data=path.join(root,"data"),secrets=path.join(root,"secrets"),pub=path.join(root,"issuer-public");fs.mkdirSync(data);fs.mkdirSync(secrets);fs.mkdirSync(pub);fs.writeFileSync(path.join(pub,"index.html"),"issuer");const config={ROOT_DIR:root,DATA_DIR:data,PRODUCT_DB_PATH:path.join(data,"p.sqlite"),ISSUER_NAME:"CKBuilder",ISSUER_LOCK_HASH:`0x${"44".repeat(32)}`,ISSUER_PRIVATE_KEY_PATH:path.join(secrets,"issuer-private.pem"),ISSUER_PUBLIC_KEY_PATH:path.join(secrets,"issuer-public.pem"),TRUSTED_ISSUERS_FILE:path.join(data,"trusted.json"),PUBLIC_BASE_URL:"http://example.test",APP_NETWORK:"devnet",CKB_RPC_URL:"http://127.0.0.1:9",CHAIN_WRITE_MODE:"disabled",ADMIN_EMAIL:"admin@example.com",ADMIN_PASSWORD:"correct horse battery staple",SESSION_SECRET:"s".repeat(48),AI_DEFAULT_PROVIDER:"openai",AI_DEFAULT_MODEL:"gpt-4.1-mini",WEBHOOK_URL:"",WEBHOOK_SECRET:""};initializeIssuer(config);const db=openProductDb(config.PRODUCT_DB_PATH);const server=createIssuerServer({config,publicDir:pub,db,logger:{error(){}}});server.listen(0,"127.0.0.1");await once(server,"listening");return{config,db,server,base:`http://127.0.0.1:${server.address().port}`}}
async function login(x){const r=await fetch(`${x.base}/api/auth/login`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:x.config.ADMIN_EMAIL,password:x.config.ADMIN_PASSWORD})});assert.equal(r.status,200);return r.headers.get("set-cookie").split(";",1)[0]}
const item=(name="Builder")=>({applicantName:name,applicantEmail:`${name.toLowerCase().replace(/\s/g,'')}@example.com`,recipientLockHash:`0x${"55".repeat(32)}`,credentialType:"Builder Milestone",credentialTitle:`${name} Type Script`,category:"CKB",evidence:["https://github.com/example/repo"]});

test("v4 issuer bulk intake, search and stats require authenticated admin",async()=>{const x=await setup();try{const cookie=await login(x);let r=await fetch(`${x.base}/api/admin/submissions/bulk`,{method:"POST",headers:{"content-type":"application/json",cookie},body:JSON.stringify({submissions:[item("Alpha"),item("Beta")]})});assert.equal(r.status,201);assert.equal((await r.json()).created.length,2);r=await fetch(`${x.base}/api/admin/submissions?q=Alpha`,{headers:{cookie}});assert.equal((await r.json()).submissions.length,1);r=await fetch(`${x.base}/api/admin/stats`,{headers:{cookie}});const stats=await r.json();assert.equal(stats.submissions.total,2);assert.equal(stats.credentials.total,0);}finally{await new Promise(r=>x.server.close(r));closeProductDb(x.db)}});

test("v4 review state guard prevents acting twice without applicant resubmission",async()=>{const x=await setup();try{const c=createSubmission(x.db,item());const cookie=await login(x);let r=await fetch(`${x.base}/api/admin/submissions/${c.id}/review`,{method:"POST",headers:{"content-type":"application/json",cookie},body:JSON.stringify({action:"request_changes",notes:"add tx"})});assert.equal(r.status,200);r=await fetch(`${x.base}/api/admin/submissions/${c.id}/review`,{method:"POST",headers:{"content-type":"application/json",cookie},body:JSON.stringify({action:"reject",notes:"no"})});assert.equal(r.status,409);assert.equal((await r.json()).error,"REVIEW_STATE_INVALID");}finally{await new Promise(r=>x.server.close(r));closeProductDb(x.db)}});

test("v4 admin export contains operational data but not auth hashes or tracking hashes",async()=>{const x=await setup();try{createSubmission(x.db,item());const cookie=await login(x);const r=await fetch(`${x.base}/api/admin/export`,{headers:{cookie}});const raw=JSON.stringify(await r.json());assert.equal(r.status,200);assert.equal(raw.includes("password_hash"),false);assert.equal(raw.includes("tracking_hash"),false);}finally{await new Promise(r=>x.server.close(r));closeProductDb(x.db)}});

test("v4 operations and webhook delivery endpoints are available to admin",async()=>{const x=await setup();try{const cookie=await login(x);let r=await fetch(`${x.base}/api/admin/operations`,{headers:{cookie}});assert.deepEqual((await r.json()).operations,[]);r=await fetch(`${x.base}/api/admin/webhooks`,{headers:{cookie}});assert.deepEqual((await r.json()).deliveries,[]);}finally{await new Promise(r=>x.server.close(r));closeProductDb(x.db)}});

test("v4 bulk endpoint rejects oversized batches",async()=>{const x=await setup();try{const cookie=await login(x);const r=await fetch(`${x.base}/api/admin/submissions/bulk`,{method:"POST",headers:{"content-type":"application/json",cookie},body:JSON.stringify({submissions:Array.from({length:51},()=>item())})});assert.equal(r.status,400);assert.equal((await r.json()).error,"BULK_INPUT_INVALID");}finally{await new Promise(r=>x.server.close(r));closeProductDb(x.db)}});
