import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { once } from "node:events";
import { createInspectorServer } from "../src/lib/inspector-http.js";
import { emptyLedger } from "../src/lib/ledger.js";
import { writeJsonAtomic } from "../src/lib/json.js";
import { closeProductDb, openProductDb } from "../src/lib/product-db.js";

const submission={applicantName:"HTML Builder",applicantEmail:"html@example.com",recipientLockHash:`0x${"22".repeat(32)}`,credentialType:"Builder Milestone",credentialTitle:"HTML Type Script",category:"CKB",evidence:["https://github.com/example/repo"]};
function record(title="Type Script Builder"){return {schema:"ckb-degree-proof-record/v1",status:"ACTIVE",payload:{schema:"ckbuilder-credential/v2",credentialId:"CKB-HTML-001",credentialType:"Builder Milestone",issuer:{issuerId:`0x${"aa".repeat(32)}`,name:"CKBuilder",lockHash:`0x${"bb".repeat(32)}`},subject:{recipientLockHash:`0x${"cc".repeat(32)}`,identityCommitment:`0x${"dd".repeat(32)}`},award:{title,field:"CKB",classification:"Builder Milestone",issuedAt:"2026-08-08"},document:{hashAlgorithm:"sha256",hash:`0x${"ee".repeat(32)}`,fileName:"certificate.html"},createdAt:"2026-08-08T00:00:00.000Z"},issuerPublicKeyPem:"public",signature:"sig"}}
async function withApp(fn,records=[]){const root=fs.mkdtempSync(path.join(os.tmpdir(),"ckbuilder-v5http-")),pub=path.join(root,"public"),data=path.join(root,"data");fs.mkdirSync(pub);fs.mkdirSync(data);fs.writeFileSync(path.join(pub,"index.html"),"<title>v5</title>");const ledger=emptyLedger();for(const r of records)ledger.credentials[r.payload.credentialId]=r;writeJsonAtomic(path.join(data,"ledger.json"),ledger);const db=openProductDb(path.join(data,"p.sqlite"));const config={ROOT_DIR:root,DATA_DIR:data,APP_NETWORK:"devnet",CKB_RPC_URL:"http://127.0.0.1:9",ISSUER_LOCK_HASH:`0x${"11".repeat(32)}`,PUBLIC_BASE_URL:"https://verify.example",AI_ENABLED:true,AI_DEFAULT_PROVIDER:"openai",AI_DEFAULT_MODEL:"gpt-4.1-mini",PUBLIC_DIRECTORY_ENABLED:false};const server=createInspectorServer({config,publicDir:pub,productDb:db,learningOverview:()=>({summary:{}}),inspectCredential:async()=>({})});server.listen(0,"127.0.0.1");await once(server,"listening");try{await fn({base:`http://127.0.0.1:${server.address().port}`,db,config})}finally{await new Promise(r=>server.close(r));closeProductDb(db);fs.rmSync(root,{recursive:true,force:true})}}
const post=(url,body)=>fetch(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});

test("v5 health and config advertise HTML/document support",async()=>withApp(async({base})=>{let b=await (await fetch(`${base}/api/health`)).json();assert.equal(b.version,"9.0.0");b=await (await fetch(`${base}/api/config`)).json();assert.equal(b.htmlSupport,true);assert.equal(b.submissionAttachments,true);assert.ok(b.supportedDocuments.includes("text/html"));}));

test("v5 document inspection endpoint sanitizes hostile HTML without AI",async()=>withApp(async({base})=>{const html='<h1>Alice</h1><script>fetch("https://evil")</script><p>Credential C-1</p>';const r=await post(`${base}/api/document/inspect`,{fileName:"credential.html",mimeType:"text/html",documentBase64:Buffer.from(html).toString("base64")});assert.equal(r.status,200);const b=await r.json();assert.match(b.textExcerpt,/Alice/);assert.doesNotMatch(b.safeHtml,/fetch\(|<script/);assert.match(b.safeHtml,/Safe preview/);}));

test("v5 applicant can upload, list and remove an HTML evidence attachment",async()=>withApp(async({base})=>{let r=await post(`${base}/api/submissions`,submission);const created=await r.json();r=await post(`${base}/api/submissions/${created.id}/attachments`,{trackingToken:created.trackingToken,fileName:"evidence.html",mimeType:"text/html",documentBase64:Buffer.from('<h1>Evidence</h1>').toString("base64")});assert.equal(r.status,201);const a=await r.json();assert.equal(a.mimeType,"text/html");r=await fetch(`${base}/api/submissions/${created.id}?token=${encodeURIComponent(created.trackingToken)}`);let tracked=await r.json();assert.equal(tracked.attachments.length,1);assert.equal(tracked.timeline.some(e=>e.event_type==="ATTACHMENT_ADDED"),true);r=await fetch(`${base}/api/submissions/${created.id}/attachments/${a.id}`,{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({trackingToken:created.trackingToken})});assert.equal(r.status,200);tracked=await (await fetch(`${base}/api/submissions/${created.id}?token=${encodeURIComponent(created.trackingToken)}`)).json();assert.equal(tracked.attachments.length,0);assert.equal(tracked.timeline.some(e=>e.event_type==="ATTACHMENT_REMOVED"),true);}));

test("v5 wrong tracking token cannot list or upload attachments",async()=>withApp(async({base})=>{const created=await (await post(`${base}/api/submissions`,submission)).json();let r=await fetch(`${base}/api/submissions/${created.id}/attachments?token=wrong`);assert.equal(r.status,404);r=await post(`${base}/api/submissions/${created.id}/attachments`,{trackingToken:"wrong",fileName:"x.html",mimeType:"text/html",documentBase64:Buffer.from("x").toString("base64")});assert.equal(r.status,404);}));

test("v5 attachment upload rejects SVG even when it contains only text",async()=>withApp(async({base})=>{const created=await (await post(`${base}/api/submissions`,submission)).json();const r=await post(`${base}/api/submissions/${created.id}/attachments`,{trackingToken:created.trackingToken,fileName:"x.svg",mimeType:"image/svg+xml",documentBase64:Buffer.from("<svg><text>x</text></svg>").toString("base64")});assert.equal(r.status,400);assert.equal((await r.json()).error,"DOCUMENT_TYPE_UNSUPPORTED");}));

test("v5 HTML credential endpoint returns printable escaped HTML and strict CSP",async()=>withApp(async({base})=>{const r=await fetch(`${base}/api/certificate/CKB-HTML-001/html`);assert.equal(r.status,200);assert.match(r.headers.get("content-type"),/text\/html/);assert.match(r.headers.get("content-security-policy"),/default-src 'none'/);assert.match(r.headers.get("content-disposition"),/\.html/);const html=await r.text();assert.match(html,/CKBUILDER PASSPORT/);assert.match(html,/Verify current status/);},[record()]));

test("v5 advertised 5 MB attachment boundary survives base64 JSON expansion",async()=>withApp(async({base})=>{const created=await (await post(`${base}/api/submissions`,submission)).json();const bytes=Buffer.alloc(5*1024*1024,0x61);const r=await post(`${base}/api/submissions/${created.id}/attachments`,{trackingToken:created.trackingToken,fileName:"max.txt",mimeType:"text/plain",documentBase64:bytes.toString("base64")});assert.equal(r.status,201);const body=await r.json();assert.equal(body.byteLength,5*1024*1024);}));

test("v5 original public inspector upload path handles a multi-megabyte canonical document without regex overflow",async()=>withApp(async({base})=>{const bytes=Buffer.alloc(5*1024*1024,0x62);const r=await post(`${base}/api/inspect`,{credentialId:"C-LARGE",documentBase64:bytes.toString("base64"),skipChain:true});assert.equal(r.status,200);}));
