import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { once } from "node:events";
import { initializeIssuer } from "../src/lib/credential-service.js";
import { storeSubmissionAttachment } from "../src/lib/attachment-service.js";
import { closeProductDb, createSubmission, openProductDb } from "../src/lib/product-db.js";
import { createIssuerServer } from "../src/lib/issuer-http.js";

async function setup(){const root=fs.mkdtempSync(path.join(os.tmpdir(),"ckbuilder-v5issuer-")),data=path.join(root,"data"),secrets=path.join(root,"secrets"),pub=path.join(root,"issuer-public");fs.mkdirSync(data);fs.mkdirSync(secrets);fs.mkdirSync(pub);fs.writeFileSync(path.join(pub,"index.html"),"issuer");const config={ROOT_DIR:root,DATA_DIR:data,PRODUCT_DB_PATH:path.join(data,"p.sqlite"),ISSUER_NAME:"CKBuilder",ISSUER_LOCK_HASH:`0x${"44".repeat(32)}`,ISSUER_PRIVATE_KEY_PATH:path.join(secrets,"issuer-private.pem"),ISSUER_PUBLIC_KEY_PATH:path.join(secrets,"issuer-public.pem"),TRUSTED_ISSUERS_FILE:path.join(data,"trusted.json"),PUBLIC_BASE_URL:"https://verify.example",APP_NETWORK:"devnet",CKB_RPC_URL:"http://127.0.0.1:9",CHAIN_WRITE_MODE:"disabled",ADMIN_EMAIL:"admin@example.com",ADMIN_PASSWORD:"correct horse battery staple",SESSION_SECRET:"s".repeat(48),AI_DEFAULT_PROVIDER:"openai",AI_DEFAULT_MODEL:"gpt-4.1-mini",WEBHOOK_URL:"",WEBHOOK_SECRET:""};initializeIssuer(config);const db=openProductDb(config.PRODUCT_DB_PATH);const server=createIssuerServer({config,publicDir:pub,db,logger:{error(){}}});server.listen(0,"127.0.0.1");await once(server,"listening");return{root,config,db,server,base:`http://127.0.0.1:${server.address().port}`}}
async function login(x){const r=await fetch(`${x.base}/api/auth/login`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:x.config.ADMIN_EMAIL,password:x.config.ADMIN_PASSWORD})});return r.headers.get("set-cookie").split(";",1)[0]}
const input={applicantName:"Alice",applicantEmail:"alice@example.com",recipientLockHash:`0x${"55".repeat(32)}`,credentialType:"Builder Milestone",credentialTitle:"Type Script Builder",category:"CKB",evidence:["https://github.com/example/repo"]};

test("v5 issuer lists attachment metadata and sanitizes HTML preview",async()=>{const x=await setup();try{const s=createSubmission(x.db,input);const a=storeSubmissionAttachment(x.config,x.db,s.id,{fileName:"proof.html",mimeType:"text/html",documentBase64:Buffer.from('<h1>Proof</h1><script>alert(1)</script><img src=x onerror=alert(2)>').toString("base64")});const cookie=await login(x);let r=await fetch(`${x.base}/api/admin/submissions/${s.id}/attachments`,{headers:{cookie}});assert.equal(r.status,200);assert.equal((await r.json()).attachments[0].sha256,a.sha256);r=await fetch(`${x.base}/api/admin/attachments/${a.id}/preview`,{headers:{cookie}});assert.equal(r.status,200);const html=await r.text();assert.match(html,/Proof/);assert.doesNotMatch(html,/<script|onerror|<img/);assert.match(r.headers.get("content-security-policy"),/default-src 'none'/);}finally{await new Promise(r=>x.server.close(r));closeProductDb(x.db);fs.rmSync(x.root,{recursive:true,force:true})}});

test("v5 raw HTML evidence is forced to attachment download with nosniff",async()=>{const x=await setup();try{const s=createSubmission(x.db,input);const raw='<script>window.top.location="https://evil"</script>';const a=storeSubmissionAttachment(x.config,x.db,s.id,{fileName:"danger.html",mimeType:"text/html",documentBase64:Buffer.from(raw).toString("base64")});const cookie=await login(x);const r=await fetch(`${x.base}/api/admin/attachments/${a.id}/download`,{headers:{cookie}});assert.equal(r.status,200);assert.equal(r.headers.get("content-type"),"application/octet-stream");assert.match(r.headers.get("content-disposition"),/^attachment;/);assert.equal(r.headers.get("x-content-type-options"),"nosniff");assert.equal(await r.text(),raw);}finally{await new Promise(r=>x.server.close(r));closeProductDb(x.db);fs.rmSync(x.root,{recursive:true,force:true})}});

test("v5 attachment integrity check detects storage tampering",async()=>{const x=await setup();try{const s=createSubmission(x.db,input);const a=storeSubmissionAttachment(x.config,x.db,s.id,{fileName:"proof.txt",mimeType:"text/plain",documentBase64:Buffer.from("original").toString("base64")});const row=x.db.prepare("SELECT storage_relpath FROM submission_attachments WHERE id=?").get(a.id);fs.writeFileSync(path.join(x.config.DATA_DIR,"product-attachments",row.storage_relpath),"tampered");const cookie=await login(x);const r=await fetch(`${x.base}/api/admin/attachments/${a.id}/download`,{headers:{cookie}});assert.equal(r.status,400);assert.equal((await r.json()).error,"ATTACHMENT_INTEGRITY_FAILED");}finally{await new Promise(r=>x.server.close(r));closeProductDb(x.db);fs.rmSync(x.root,{recursive:true,force:true})}});

test("v5 unauthenticated users cannot preview private submission attachments",async()=>{const x=await setup();try{const s=createSubmission(x.db,input);const a=storeSubmissionAttachment(x.config,x.db,s.id,{fileName:"proof.html",mimeType:"text/html",documentBase64:Buffer.from("<p>private</p>").toString("base64")});const r=await fetch(`${x.base}/api/admin/attachments/${a.id}/preview`);assert.equal(r.status,401);}finally{await new Promise(r=>x.server.close(r));closeProductDb(x.db);fs.rmSync(x.root,{recursive:true,force:true})}});

test("v5 authenticated attachment audit endpoint reports storage health",async()=>{const x=await setup();try{const s=createSubmission(x.db,input);storeSubmissionAttachment(x.config,x.db,s.id,{fileName:"proof.txt",mimeType:"text/plain",documentBase64:Buffer.from("healthy").toString("base64")});const cookie=await login(x);const r=await fetch(`${x.base}/api/admin/attachments/audit`,{headers:{cookie}});assert.equal(r.status,200);const body=await r.json();assert.equal(body.ok,true);assert.equal(body.checked,1);}finally{await new Promise(r=>x.server.close(r));closeProductDb(x.db);fs.rmSync(x.root,{recursive:true,force:true})}});
