import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { once } from "node:events";
import { fileURLToPath } from "node:url";
import { createInspectorServer } from "../src/lib/inspector-http.js";
const repoRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");const html=fs.readFileSync(path.join(repoRoot,"public","index.html"),"utf8"),app=fs.readFileSync(path.join(repoRoot,"public","app.js"),"utf8");
function jr(v){return new Response(JSON.stringify(v),{status:200,headers:{"content-type":"application/json"}})}function ai(t){return jr({choices:[{message:{content:t}}]})}function tx(){return {version:"0x0",cell_deps:[],header_deps:[],inputs:[{previous_output:{tx_hash:`0x${"22".repeat(32)}`,index:"0x0"},since:"0x0"}],outputs:[{capacity:"0x100",lock:{code_hash:`0x${"33".repeat(32)}`,hash_type:"type",args:"0x"},type:null}],outputs_data:["0x"],witnesses:["0x"]};}
async function withApp(fn,over={}){const root=fs.mkdtempSync(path.join(os.tmpdir(),"ckbuilder-v9http-")),pub=path.join(root,"public"),data=path.join(root,"data");fs.mkdirSync(pub);fs.mkdirSync(data);fs.writeFileSync(path.join(pub,"index.html"),"x");const config={ROOT_DIR:repoRoot,DATA_DIR:data,APP_NETWORK:"testnet",CKB_RPC_URL:"http://127.0.0.1:8114",FIBER_RPC_URL:"",CKB_AGENT_WORKSPACE:"",CKB_GITHUB_TOKEN:"SECRET",PUBLIC_BASE_URL:"http://x",AI_ENABLED:true,AI_DEFAULT_PROVIDER:"openai",AI_DEFAULT_MODEL:"gpt-4.1-mini",PUBLIC_DIRECTORY_ENABLED:false};const server=createInspectorServer({config,publicDir:pub,learningOverview:()=>({summary:{}}),inspectCredential:async()=>({}),aiFetchImpl:async()=>ai("done"),...over});server.listen(0,"127.0.0.1");await once(server,"listening");try{await fn(`http://127.0.0.1:${server.address().port}`)}finally{await new Promise(r=>server.close(r));fs.rmSync(root,{recursive:true,force:true});}}

test("v9 agent run persists a private retrievable job and config exposes aggregate reputation only",async()=>withApp(async base=>{const r=await fetch(`${base}/api/agent-commerce/run`,{method:"POST",headers:{"content-type":"application/json","x-ai-api-key":"key","x-ai-provider":"openai"},body:JSON.stringify({serviceId:"ckb-verifiable-research",objective:"private alpha"})});const body=await r.json();assert.ok(body.jobAccess.jobAccessToken);const job=await (await fetch(`${base}/api/agent-commerce/jobs/${body.jobAccess.jobId}?token=${encodeURIComponent(body.jobAccess.jobAccessToken)}`)).json();assert.equal(job.objective,"private alpha");const cfg=await (await fetch(`${base}/api/config`)).json();const svc=cfg.agentServices.find(x=>x.id==="ckb-verifiable-research");assert.equal(svc.reputation.jobs,1);assert.equal(JSON.stringify(cfg).includes("private alpha"),false);assert.equal(JSON.stringify(cfg).includes("SECRET"),false);}));

test("v9 HTTP verifies receipts and preflights transactions without broadcast",async()=>{const methods=[];await withApp(async base=>{const run=await (await fetch(`${base}/api/agent-commerce/run`,{method:"POST",headers:{"content-type":"application/json","x-ai-api-key":"k","x-ai-provider":"openai"},body:JSON.stringify({serviceId:"ckb-verifiable-research",objective:"x"})})).json();const verify=await (await fetch(`${base}/api/agent-commerce/verify-receipt`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({receipt:run.receipt,agreement:run.agreement,fulfillment:run.fulfillment})})).json();assert.equal(verify.valid,true);const pre=await (await fetch(`${base}/api/agent-commerce/transaction-preflight`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({transaction:tx()})})).json();assert.equal(pre.dryRun.status,"ok");const doctor=await (await fetch(`${base}/api/agent-commerce/doctor`)).json();assert.equal(doctor.schema,"ckbuilder-agent-runtime-doctor/v1");},{toolFetchImpl:async(_u,o)=>{const b=JSON.parse(o.body);methods.push(b.method);return jr({jsonrpc:"2.0",id:1,result:{cycles:"0x1"}})}});assert.deepEqual(methods,["dry_run_transaction"]);});

test("v9 UI exposes runtime doctor, private job reopen/export, receipt verification and transaction preflight",()=>{for(const id of ["agent-service-agreement-preview","agent-runtime-doctor","verify-latest-agent-receipt","export-latest-agent-pack","recent-agent-jobs","ckb-tx-preflight-form","ckb-tx-preflight-json","ckb-tx-preflight-output"])assert.match(html,new RegExp(`id="${id}"`));assert.match(app,/\/api\/agent-commerce\/agreement/);assert.match(app,/Accept service agreement/);assert.match(app,/\/api\/agent-commerce\/doctor/);assert.match(app,/\/api\/agent-commerce\/verify-receipt/);assert.match(app,/\/api\/agent-commerce\/transaction-preflight/);assert.match(app,/ckbuilder-agent-jobs/);assert.match(app,/sessionStorage/);assert.match(app,/ckbuilder-agent-evidence-pack\/v1/);assert.match(app,/service\.reputation/);});


test("v9 HTTP exposes a pre-execution agreement and rejects tampering before model execution",async()=>{let aiCalls=0;await withApp(async base=>{const preview=await (await fetch(`${base}/api/agent-commerce/agreement`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({serviceId:"ckb-verifiable-research",objective:"bound objective",maxSteps:4})})).json();assert.equal(preview.agreement.executionTerms.autonomousSpend,false);const bad={...preview.agreement,executionTerms:{...preview.agreement.executionTerms,broadcastAuthority:true}};const response=await fetch(`${base}/api/agent-commerce/run`,{method:"POST",headers:{"content-type":"application/json","x-ai-api-key":"key","x-ai-provider":"openai"},body:JSON.stringify({serviceId:"ckb-verifiable-research",objective:"bound objective",agreement:bad})});assert.equal(response.status,400);const body=await response.json();assert.equal(body.error,"AGENT_SERVICE_AGREEMENT_MISMATCH");},{aiFetchImpl:async()=>{aiCalls+=1;return ai("should not run")}});assert.equal(aiCalls,0);});
