const $=(s)=>document.querySelector(s); let config={}; let ai={key:"",provider:"openai",model:""};
async function json(url,options={}){const r=await fetch(url,{...options,headers:{"content-type":"application/json",...(options.headers||{})}});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.message||b.error||`HTTP ${r.status}`);return b}
function aiHeaders(){return ai.key?{"x-ai-api-key":ai.key,"x-ai-provider":ai.provider||"auto",...(ai.model?{"x-ai-model":ai.model}:{})}:{} }
async function boot(){config=await json('/api/config');$('#network').textContent=`${config.network} · ${config.chainWriteMode}`;const p=$('#ai-provider');for(const x of config.aiProviders||[]){const o=document.createElement('option');o.value=x.id;o.textContent=x.name;p.append(o)}if(!(config.aiProviders||[]).some(x=>x.id===ai.provider))ai.provider=config.aiDefaultProvider||'openai';if(!ai.model)ai.model=(config.aiProviders||[]).find(x=>x.id===ai.provider)?.defaultModel||config.aiDefaultModel||'';p.value=ai.provider;$('#ai-model').value=ai.model;try{await json('/api/admin/me');showApp()}catch{}}
function showApp(){$('#login-card').classList.add('hidden');$('#app').classList.remove('hidden');switchTab('dashboard')}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const st=$('#login-status');try{await json('/api/auth/login',{method:'POST',body:JSON.stringify({email:$('#login-email').value,password:$('#login-password').value})});st.textContent='';showApp()}catch(err){st.textContent=err.message}})
$('#logout').addEventListener('click',async()=>{await json('/api/auth/logout',{method:'POST',body:'{}'}).catch(()=>{});location.reload()})
function switchTab(name){for(const el of document.querySelectorAll('[id^="tab-"]'))el.classList.toggle('hidden',el.id!==`tab-${name}`);for(const b of document.querySelectorAll('nav [data-tab]'))b.classList.toggle('active',b.dataset.tab===name);if(name==='dashboard')loadDashboard();if(name==='submissions')loadSubmissions();if(name==='credentials')loadCredentials();if(name==='operations')loadOperations();if(name==='webhooks')loadWebhooks();if(name==='audit')loadAudit()}
for(const b of document.querySelectorAll('[data-tab]'))b.addEventListener('click',()=>switchTab(b.dataset.tab));
function stat(label,value){const a=document.createElement('article');a.className='stat-card';const s=document.createElement('span');s.textContent=label;const b=document.createElement('strong');b.textContent=String(value??0);a.append(s,b);return a}
async function loadDashboard(){const s=await json('/api/admin/stats');const box=$('#dashboard-stats');box.replaceChildren(stat('Submissions',s.submissions?.total),stat('Pending review',s.submissions?.byStatus?.SUBMITTED||0),stat('Active credentials',s.credentials?.active||0),stat('Revoked',s.credentials?.revoked||0),stat('Profiles',s.profiles),stat('Operations',s.operations?.total),stat('Audit events',s.auditEvents),stat('Evidence files',s.attachments||0),stat('Failed operations',s.operations?.byStatus?.FAILED||0))}
async function loadSubmissionAttachments(id,box){try{const r=await json(`/api/admin/submissions/${encodeURIComponent(id)}/attachments`);box.replaceChildren();if(!(r.attachments||[]).length){const small=document.createElement('small');small.textContent='No uploaded files.';box.append(small);return}const title=document.createElement('strong');title.textContent='Uploaded evidence files';box.append(title);for(const a of r.attachments){const row=document.createElement('div');row.className='attachment-row';const meta=document.createElement('span');meta.textContent=`${a.fileName} · ${a.mimeType} · ${Math.ceil(a.byteLength/1024)} KB · ${a.sha256.slice(0,12)}…`;const preview=document.createElement('a');preview.href=`/api/admin/attachments/${encodeURIComponent(a.id)}/preview`;preview.target='_blank';preview.rel='noopener';preview.textContent='Safe preview';const download=document.createElement('a');download.href=`/api/admin/attachments/${encodeURIComponent(a.id)}/download`;download.textContent='Download raw';row.append(meta,preview,download);box.append(row)}}catch(e){box.textContent=`Attachments unavailable: ${e.message}`}}
async function loadSubmissions(){const q=$('#submission-search')?.value.trim()||'',status=$('#submission-status-filter')?.value||'';const params=new URLSearchParams();if(q)params.set('q',q);if(status)params.set('status',status);const {submissions}=await json(`/api/admin/submissions?${params}`);const box=$('#submissions');box.replaceChildren();for(const s of submissions){const a=document.createElement('article');a.className='submission';const left=document.createElement('div');const title=document.createElement('h3');title.textContent=`${s.credential_title} · ${s.applicant_name}`;left.append(title);const meta=document.createElement('div');meta.className='meta';for(const [k,v] of [['Status',s.status],['Type',s.credential_type],['Category',s.category]]){const d=document.createElement('div'),sp=document.createElement('span'),st=document.createElement('strong');sp.textContent=k;st.textContent=v;d.append(sp,st);meta.append(d)}left.append(meta);const lock=document.createElement('p'),code=document.createElement('code');code.textContent=s.recipient_lock_hash;lock.append('Recipient: ',code);left.append(lock);const ul=document.createElement('ul');ul.className='evidence';for(const ev of s.evidence||[]){const li=document.createElement('li');li.textContent=ev;ul.append(li)}left.append(ul);if(s.notes){const p=document.createElement('p');p.textContent=s.notes;left.append(p)}if(s.reviewer_notes){const p=document.createElement('p');p.textContent=`Reviewer: ${s.reviewer_notes}`;left.append(p)}if(s.ai?.text){const pre=document.createElement('div');pre.className='ai';pre.textContent=s.ai.text;left.append(pre)}const attachments=document.createElement('div');attachments.className='attachments';left.append(attachments);loadSubmissionAttachments(s.id,attachments);const actions=document.createElement('div');actions.className='row-actions';const checkBtn=document.createElement('button');checkBtn.textContent='Run checks';checkBtn.onclick=()=>runChecks(s.id,checkBtn);const aiBtn=document.createElement('button');aiBtn.textContent='AI triage';aiBtn.onclick=()=>triage(s.id,aiBtn);actions.append(checkBtn,aiBtn);if(s.status==='SUBMITTED'){for(const [label,action,cls] of [['Approve & issue','approve',''],['Request changes','request_changes','warn'],['Reject','reject','danger']]){const b=document.createElement('button');b.textContent=label;if(cls)b.className=cls;b.onclick=()=>review(s.id,action);actions.append(b)}}left.append(actions);a.append(left);box.append(a)}if(!submissions.length)box.textContent='No matching submissions.'}
async function runChecks(id,b){b.disabled=true;try{const r=await json(`/api/admin/submissions/${encodeURIComponent(id)}/check`,{method:'POST',body:'{}'});alert(JSON.stringify(r.summary,null,2));await loadSubmissions()}catch(e){alert(e.message)}finally{b.disabled=false}}
async function triage(id,b){if(!ai.key){$('#ai-dialog').showModal();return}b.disabled=true;try{await json(`/api/admin/submissions/${encodeURIComponent(id)}/ai`,{method:'POST',body:'{}',headers:aiHeaders()});await loadSubmissions()}catch(e){alert(e.message)}finally{b.disabled=false}}
async function review(id,action){const notes=prompt(action==='approve'?'Optional reviewer note:':'Reviewer note / reason:')??'';if(action!=='approve'&&!notes.trim())return;try{const r=await json(`/api/admin/submissions/${encodeURIComponent(id)}/review`,{method:'POST',body:JSON.stringify({action,notes})});if(r.credentialId)alert(`Issued ${r.credentialId}\nStatus: ${r.status}`);await loadSubmissions();await loadDashboard()}catch(e){alert(e.message)}}
async function loadCredentials(){const {credentials}=await json('/api/admin/credentials');const box=$('#credentials');box.replaceChildren();for(const c of credentials){const a=document.createElement('article');a.className='credential';const h=document.createElement('h3');h.textContent=c.credentialSubject.achievement.name;const p=document.createElement('p');p.textContent=`${c.credentialStatus.status} · ${c.validFrom.slice(0,10)}`;const code=document.createElement('code');code.textContent=c.id;const html=document.createElement('a');html.href=`${config.publicBaseUrl||''}/api/certificate/${encodeURIComponent(c.ckbuilderProof.signedPayload.credentialId)}/html`;html.target='_blank';html.rel='noopener';html.textContent='HTML certificate';const b=document.createElement('button');b.className='danger';b.textContent='Revoke';b.disabled=c.credentialStatus.status==='REVOKED';b.onclick=async()=>{const reason=prompt('Revocation reason:');if(!reason)return;const id=c.ckbuilderProof.signedPayload.credentialId;try{await json(`/api/admin/credentials/${encodeURIComponent(id)}/revoke`,{method:'POST',body:JSON.stringify({reasonCode:1,reason})});await loadCredentials();await loadDashboard()}catch(e){alert(e.message)}};a.append(h,p,code,html,b);box.append(a)}if(!credentials.length)box.textContent='No credentials issued.'}
async function loadOperations(){const r=await json('/api/admin/operations');$('#operations').textContent=JSON.stringify(r.operations,null,2)}
async function loadWebhooks(){const r=await json('/api/admin/webhooks');$('#webhooks').textContent=config.webhookEnabled?JSON.stringify(r.deliveries,null,2):'Webhooks are disabled. Set WEBHOOK_URL and WEBHOOK_SECRET in the private issuer environment to enable signed notifications.'}
async function loadAudit(){const r=await json('/api/admin/audit');$('#audit').textContent=JSON.stringify(r.events,null,2)}
$('#bulk-submit').onclick=async()=>{const out=$('#bulk-output');try{const parsed=JSON.parse($('#bulk-json').value);const submissions=Array.isArray(parsed)?parsed:parsed.submissions;const r=await json('/api/admin/submissions/bulk',{method:'POST',body:JSON.stringify({submissions})});out.textContent=JSON.stringify(r,null,2);out.classList.remove('hidden');await loadDashboard()}catch(e){out.textContent=e.message;out.classList.remove('hidden')}};
$('#audit-attachments').onclick=async()=>{const st=$('#attachment-audit-status');try{const r=await json('/api/admin/attachments/audit');st.textContent=r.ok?`Attachment storage healthy · ${r.checked} checked`:`Attachment problems · missing ${r.missing.length}, tampered ${r.tampered.length}, orphaned ${r.orphaned.length}`;st.className=r.ok?'status ok':'status error'}catch(e){st.textContent=e.message;st.className='status error'}};
$('#refresh-dashboard').onclick=loadDashboard;$('#refresh-submissions').onclick=loadSubmissions;$('#refresh-credentials').onclick=loadCredentials;$('#refresh-operations').onclick=loadOperations;$('#refresh-webhooks').onclick=loadWebhooks;$('#refresh-audit').onclick=loadAudit;$('#submission-search').addEventListener('input',()=>{clearTimeout(window.__searchTimer);window.__searchTimer=setTimeout(loadSubmissions,250)});$('#submission-status-filter').onchange=loadSubmissions;
$('#ai-settings').onclick=()=>$('#ai-dialog').showModal();$('#ai-provider').onchange=()=>{$('#ai-model').value=(config.aiProviders||[]).find(x=>x.id===$('#ai-provider').value)?.defaultModel||''};$('#save-ai').onclick=()=>{ai={key:$('#ai-key').value.trim(),provider:$('#ai-provider').value,model:$('#ai-model').value.trim()};sessionStorage.setItem('ckbuilder-ai',JSON.stringify({provider:ai.provider,model:ai.model}));};
try{const saved=JSON.parse(sessionStorage.getItem('ckbuilder-ai')||'null');if(saved)ai={...ai,...saved}}catch{}
boot().catch(e=>{$('#login-status').textContent=e.message});
